"""Initial migration.

Revision ID: 1861e3edad85
Revises: 
Create Date: 2022-05-30 23:09:28.650491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1861e3edad85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('first_name', sa.String(length=128), nullable=True))
    op.add_column('student', sa.Column('last_name', sa.String(length=128), nullable=True))
    op.drop_column('student', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('student', 'last_name')
    op.drop_column('student', 'first_name')
    # ### end Alembic commands ###
